### ISSUE TITLE
Crits on the way?

### ISSUE THREAD

**Issue by r3comp1le** [daverstephens/The-SOC-Shop#1]
Crits install script would be awesome!

**Comment by daverstephens** [comment]
Hi, no CRITS yet but it is planned - Sadly I've been sidetracked by other
work at the moment but watch this space :)

**Comment by elhoim** [comment]
https://github.com/petiepooo/docker-crits Might be of interest

**Comment by daverstephens** [comment]
Thanks David, I'm going to take a look!

**Comment by daverstephens** [comment]
Looks like I've been beaten to an install script for quick testing by the CRITS team...

https://github.com/crits/crits/blob/master/script/bootstrap
